config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	validates :image, presence: true
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
 
  def index
    @posts = Post.order('created_at DESC')
  end
 
  def show
  end
 
  def new
    @post = Post.new
  end
 
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end
 
  def edit
  end
 
  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to posts_path
    end
 
  private
 
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
 
  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogtask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <ul class="alert alert-danger alert-dismissible" role="alert">
        <h6>
          <%= pluralize(@post.errors.count, "error") %> prohibited
          this post from being saved:
        </h6>
        <% @post.errors.full_messages.each do |msg| %>
          <li class="mx-4"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div><br>
 
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div><br>
 
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div><br>
 
  <button class="btn btn-primary" type='<%= f.submit %>'>Create</button>
<% end %>

app/views/posts/_post.html.erb
<div class="card mt-2 col-md-6 col-lg-4">
	<img 
		src="<%= post.image.thumb.url %>"
		class="card-img-top mx-auto"
		style="max-height: 200px;"
		alt="post.title"
		loading="lazy"
	>
	<div class="card-body">
		<a class="card-title" href="<%= post_path(post) %>"><%= truncate(post.title, length: 20) %></a>
		<p class="card-text"><%= truncate(post.body, length: 150) %></p>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Edit post</h1>
	 
	<%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container mx-auto bg-light">
	<h1>Posts</h1>
	<div class="sticky-top my-3 bg-light w-100 py-2">
		<a class="btn btn-success" href="<%= new_post_path %>" role="button">Add post</a>
	</div>

	<div class="row px-4">
		<%= render @posts %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>Add post</h1>

	<%= render 'form', post: @post %>
</div> 

app/views/posts/show.html.erb
<div class="container">    
    <%= link_to 'All posts', posts_path %>
    <h1><%= @post.title %></h1>

    <div class="card mx-auto">
        <img
            class="mx-auto"
            src="<%= @post.image.url %>"
            style="max-height: 600px; max-width: 600px;"
        >

        <div class="card-body">
            <p><%= @post.body %></p>
        </div>
    </div>
    <div class="row fixed-bottom">
        <%= link_to('Edit', edit_post_path(@post), class: "btn btn-success col") %>
        <%= link_to('Destroy', post_path(@post),method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger col") %>
    </div> 
</div>